# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: jjarfi
google_analytics: ""
title: Jeremia Jarfi

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Jeremia Jarfi

description: Stylish Jekyll Theme
author:
  name: Jeremia Jarfi
  email: pacelinux@gmail.com
  github: jjarfi
  twitter: ""
  pinterest: ""
  linkedin: ""
  bio: Life, Learn & Coding
  academia: s200_jerry.j.jpg

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
